README.md
Just a suggestion to be less ranty 😊
Guess people get what you’re trying to say.
Love, Michael :octocat:
=> Reduce exclamation marks

index.d.ts, package.json, test/types/test.ts, test/types/tsconfig.json
=> add TypeScript defs

lib/prompt.js
=> feat: add options.term, closes #50

.verb.md, README.md, index.js
allow options.skip to be boolean, closes #54
=> feat: allow options.skip to be boolean

index.d.ts, test/types/test.ts
=> polish TypeScript definition file

index.d.ts, test/types/test.ts
Follow up the changes of source code.
=> Update TS types

test/type.boolean.js
Added failing tests for #78 issue as a starting point.
=> Add tests for #78

examples/autocomplete/option-footer.js, examples/autocomplete/prompt.js, examples/confirm/option-istrue.js, examples/list/option-result.js, examples/password/option-footer.js, lib/types/array.js
this example filters out the empty string which gets added as the last element
closes #144
=> example fixes

examples/enquirer/questions.js
Fix Assertion Error thrown by enquirer-prompt.js which was caused
by wrong prompt type mentioned in questions.js file.
Closes #168
=> fix: enquirer/enquirer-prompt.js

lib/types/number.js
Resolve bug that changes number to 0 (zero) when decimal (.) is entered.
Closes #170
=> fix: types/number.js

examples/autocomplete/option-highlight.js, examples/confirm/enquirer-option-default.js
- fix: confirm/enquirer-option-default.js
Call string functions only on string input
Resolves #167 
- fix: autocomplete/option-highlight.js
Resolves #137
=> fix: Prompt example fixes

examples/enquirer/custom-prompt-standalone.js
=> fix: custom-prompt-standalone

examples/enquirer/custom-prompt-plugin-function.js
=> fix: enquirer/custom-prompt-plugin-function.js

examples/input/option-symbols.js
=> fix: input/option-symbols.js

lib/types/number.js
=> fix: lib/types/number.js

lib/prompts/list.js
=> fix: lib/prompts/list.js

examples/enquirer/2-factor-authentication/generateSecret.js, examples/package.json
=> feat: Generate QR code when creating new secret for two-factor authentication

lib/prompts/editable.js
Implement validate() function in editable.js to not accept input if there are errors.
Closes #139
=> feat: lib/prompts/editable.js

docs/prompts.md
Documentation for the new Quiz prompt added in #190
=> docs: Add documentation for newly added Quiz prompt

docs/prompts.md
Documentation for the new Auth prompt and BasicAuth prompt added in #193
=> docs: Add documentation for Auth Prompt and BasicAuth Prompt

examples/number/option-format.js, examples/numeral/option-format.js
=> fix: numeral/option-format.js

README.md
this is an awesome feature! make sure people know it exists!
=> document Input history feature

README.md
document how to actually get back the `value` field  from the prompt
struggled to figure this out until i dug through the tests.
=> document how to actually get back the `value` field

examples/select/option-select-color.js
**Please check if the PR fulfills these requirements**
**What kind of change does this PR introduce?** 
- In these Pull Request, I have added the fix for changing the color of the selected choice
**What is the current behavior?**
- The current behavior is just pointing the checks in the selected index
**What is the new behavior?**
- Users can easily see the choice that has been selected by them.
Fixes: #176 
**Other Information**:
=> example: Change color in Multiselect box

examples/multiselect/option-validate.js
Add a new example to showcase validation with the `MultiSelect` prompt.
=> 📦 NEW: Example MultiSelect Validate

README.md
Format it as "Built-In Prompts".
=> Fix links to "Custom Prompts" in README

README.md
=> fix:link of `Options`

README.md
Hi there!
Yesterday I was trying to implement an AutoComplete prompt using the `suggest` function, but I got confused by the explanation of the default value. At first, I thought I had to implement a matcher function comparing two strings, but then I realized the sense of the sentence.
Anyway, I tried to propose a valid alternative, hope you like it!
Best
=> edit: clarify AutoComplete suggest option in README.md 

README.md
Pluralized `question` variable in doc for multiple question prompts
=> Minor Semantic Update to README

lib/types/array.js, test/prompt.autocomplete.js
fixes https://github.com/atlassian/changesets/issues/553
=> Fixed an issue with Autcomplete crashing when pressing space when multiple choices are enabled and when no suggestions are rendered

index.d.ts, test/types/test.ts
- Added missing typings for "toggle" prompt
- Added missing typings for Choice interface
=> Added some missing types to index.d.ts
