README.md
As it stands the current custom prompt example doesn't set an initial value because the constructor is looking for a value called `sprays`. Another possible fix is to rename the `initial` prompt to `sprays` while setting up the prompt; however, it seems better to me to make custom prompts that match conventions set by the default set of prompts.
=> fix custom prompt example

lib/prompt.js
If the `valiate` function of a question returns `false`, an error will occur. This PR fixes this problem.
=> allow returning false in validation

package.json
Currently, the TypeScript types are not included in the npm package.
This PR adds the files to the files array in package.json.
=> Add type definitions to files published to npm

lib/keypress.js, test/prompt.childprocess.js, test/support/child_process.js
Hi, enquirer is awesome but when I use it in child_process, it throw this error
```
(node:81812) UnhandledPromiseRejectionWarning: Error: Invalid stream passed
at Function.keypress.listen (/Users/wanghx/Workspace/larva-team/common-bin-plus/node_modules/enquirer/lib/keypress.js:191:11)
at Input.start (/Users/wanghx/Workspace/larva-team/common-bin-plus/node_modules/enquirer/lib/prompt.js:169:28)
at Input.initialize (/Users/wanghx/Workspace/larva-team/common-bin-plus/node_modules/enquirer/lib/prompt.js:196:16)
at Promise (/Users/wanghx/Workspace/larva-team/common-bin-plus/node_modules/enquirer/lib/prompt.js:212:18)
at process._tickCallback (internal/process/next_tick.js:68:7)
at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
at startup (internal/bootstrap/node.js:285:19)
at …
```
=> Fix: prompt in child_process

examples/list/option-no-empty-string.js
Add a list prompt example that filters out all the empty strings in the resulting array.
Closes #174
=> add: list/option-no-empty-string.js

lib/styles.js
Add setter and getter functions for heading in lib/styles.js which is required by the survey prompt.
Resolves #140
=> fix: examples/survey/prompt.js

lib/prompts/editable.js
Add number() function to accept numeral input in 'editable' prompts.
Hence, fix a bug in examples/editable/prompt.js, mentioned in #139
=> fix: lib/prompts/editable.js

examples/enquirer/2-factor-authentication/config.js, examples/enquirer/2-factor-authentication/generateSecret.js, examples/enquirer/2-factor-authentication/hotp.js, examples/enquirer/2-factor-authentication/index.js, examples/enquirer/2-factor-authentication/questions.js, examples/enquirer/2-factor-authentication/totp.js, examples/package.json
Adds a new prompt example to demonstrate two-factor authentication using OTP generated by Google Authenticator.
Contains code to generate:
- Time-Based One Time Password (TOTP) using the algorithm specified in [RFC 6238](https://tools.ietf.org/html/rfc6238)
- HMAC-based One Time Password (HOTP) using the algorithm specified in [RFC 4226](https://tools.ietf.org/html/rfc4226)
The prompt example verifies Time-Based OTP generated by any Google Authenticator app using a shared secret.
A new secret can also be generated from the code.
=> feat: Add two-factor authentication using TOTP

lib/prompts/autocomplete.js
If combined with fuzzy match library like [Fuse.js](https://fusejs.io/) as autocomplete `suggest` function, `highlight` duplicates `choice.message` strings unexpectedly.
<details>
<summary><strong>Minimal reproducible example</strong></summary>
``` javascript
const {AutoComplete} = require('enquirer');
const Fuse = require('fuse.js');
const choices = [
'foobarbaz',
'bar',
'baz',
'xxx',
].map(s => ({
name: s,
message: s,
value: s,
}));
const fuse = new Fuse(choices, {keys: ['message']});
const p = new AutoComplete({
name: 'highlight-bug',
suggest: input => fuse.search(input),
choices,
})
p.run()
.then(console.log)
.catch(console.error)
;
```
</details>
ref: https://github.com/Rich-Harris/degit/pull/109
=> fix prompts/autocomplete

README.md
Resolves:#238
- fix the code snippets in the documentation
- fix the **return** information for **NumberPrompt** & **StringPrompt**
- added snippet for **BooleanPrompt**
- added snippet for **NumberPrompt**
- added snippet for **StringPrompt**
=> doc: Syntax errors in code snippets

index.d.ts
Extending the ambient interface results in an error:
TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?
By importing `EventEmitter` from `"events"`, the error goes away.
=> Fix TypeScript compiler error

lib/prompts/autocomplete.js, lib/types/array.js, test/prompt.autocomplete.js
Switches the behaviour of typing a number in the array-based prompts to appending it to the input normally, if one has already typed other text.
Should fix #237 and fix #199.  
~~Does not address #112 however.~~ Now fixes #112
=> fix: append number to input if exists, in array prompt

index.d.ts
- was no mention of the template arg
- Basetype was overriding validate on snippet (line 87)
=> Fix snippet types

README.md
Initial is currently not mentioned on the readme, but works fine when passed into the `AutoComplete` prompt.
Adds `initial` to the `AutoComplete` docs
=> Add initial to AutoComplete arguments

package.json
Enquirer uses old version. Also congrats on eslint adoption.
Here are changes in v3 -> v4
https://github.com/doowb/ansi-colors/commit/0f15d780100e07213182f856efbf0e58fe57f49c
https://github.com/doowb/ansi-colors/commit/e66ed2faab2461f3f4a7ac161a81a9b1f4b926b1
=> Upgrade ansi-colors

index.d.ts
When using .validate with promises/async, the return type needs to allow the function to return boolean or string, rather than just boolean or just string. Otherwise, the string option isn't useful (since you can return a string as an error, but can't return true to indicate a valid prompt).
Thanks for a great library!
=> Fix .validate promise return type

.verb.md, README.md
I found myself clicking multiple times on the _Built-in Prompts_ link in the Getting started section of the README, which contained an incorrect anchor link. This PR corrects that.
=> chore(docs): fix readme anchor for built in prompts

README.md
I think issue #121 wouldn't have existed if the use of the `message` property in choices was shown in the readme examples.
=> Add alternate label examples to readme

lib/prompts/form.js
Remove duplicate hint in form choices
=> fix: duplicate hint in form

lib/types/array.js
Nice to meet you!
My name is @lef237 living in Japan and I am using Enquirer.
I am using Enquirer and would like to report a bug I found.
Specifically, when I return numeric data inside `result()` and the numeric value is the same as `this.initial`, even if `this.input` is an empty string `""`, the empty string is passed to `then()`. 
This problem has caused me to have trouble when I want to pass a numeric value from `result()` into `then()`. I wanted to pass a numerical value to be processed, but an empty string was passed, resulting in an error.
Of course, if the number passed by return statement is different from `this.initial`, then the expected number is passed to `then()` without problems. This is predictable behavior.
So I thought of a improvement plan.
I modified the code to …
=> Resolved a problem in which a number passed by return statement inside result() would change to an empty string inside then().

index.d.ts
The backing code for ArrayPrompt works if any individual choice is a string or expanded object, but the typings require all choices to be either a string or Choice object. This PR updates the typings, such that a single element may be expanded as needed.
Fixes: #https://github.com/enquirer/enquirer/issues/202
=> fix: ArrayPromptOptions['choices'] should accept a combination of strings or Choice objects

lib/ansi.js, lib/interpolate.js, lib/prompt.js, lib/prompts/form.js, lib/prompts/scale.js, lib/prompts/snippet.js, lib/types/array.js, package.json, test/prompt.input.js, test/prompt.js, test/prompt.multiselect.js
If a select has messages that contain terminal links (see Anchor in https://iterm2.com/documentation-escape-codes.html), then enquirer's width calculation is incorrect. It uses `ansi-colors.unstyle` to strip off ansi control characters. It appears that that npm does not understand this anchor extension. `strip-ansi` does.
The fix is to switch from `colors.unstyle` to `strip-ansi`
> Note: I realize that this is project is not merging PRs at this point, but I'm putting this out there in case it helps others.
=> fix: improve support for terminal-link in messages

lib/types/array.js, test/prompt.multiselect.js
the `g` function was passed the current key (the string "g"), which overrided the choice param, and caused an error:
`TypeError: Cannot create property 'enabled' on string 'g'`
I've also included supporting tests.
=> fix: pressing 'g' correctly toggles nested groups

lib/prompt.js, lib/utils.js
Closes #372 
- rework utils.onExit to return a release function that cleans up process event listeners
- cursorHide call cursorShow on 'close'
- cursorHide release it's onExit callback on 'close'
=> add onExit cleanup

index.d.ts
Choices may have any value, not just strings.
=> Fix choice value type

examples/confirm/format-yes-no.js
- Adding a Confirm example showing  "yes/no" as format instead of the default "true/false".
Hopefully, this helps showcase how you can create a "yes/no" question versus a "true/false" confirm statement.
=> Format Confirm as "yes/no"

index.d.ts
Seems like this is allowed - we use it in Changesets for example [here](https://github.com/atlassian/changesets/blob/0f0b6ad10744de9a8a32305796bd78d33bb1a426/packages/cli/src/utils/cli-utilities.ts#L35) and it works.
=> Add `prefix` property to the `BasePromptOptions` type

lib/types/string.js
Fix syntax incompatibility with Node 12 & 14, the tests passed in Node v12.22.10 and v14.20.0.
Please refer to #432 and #431 for more details.
=> fix: syntax incompatibility with Node 12 & 14
